const LP_ICONS = Object.freeze({
  ETH: '/assets/images/lp-icons/ETH.png',
  CABBAGE: '/assets/images/lp-icons/CABBAGE.png',
  PNG: '/assets/images/lp-icons/PNG.png',
  AVAX: '/assets/images/lp-icons/AVAX.png',
  SNOB: '/assets/images/lp-icons/SNOWBALL.png',
  LINK: '/assets/images/lp-icons/LINK.png',
  SUSHI: '/assets/images/lp-icons/SUSHI.png',
  WBTC: '/assets/images/lp-icons/WBTC.png',
  USDT: '/assets/images/lp-icons/USDT.png',
  DAI: '/assets/images/lp-icons/DAI.png',
  AAVE: '/assets/images/lp-icons/AAVE.png',
  UNI: '/assets/images/lp-icons/UNI.png',
  YFI: '/assets/images/lp-icons/YFI.png',
  FRAX: '/assets/images/lp-icons/FRAX.png',
  TUSD: '/assets/images/lp-icons/TUSD.png',
  BUSD: '/assets/images/lp-icons/BUSD.png',
  SPORE: '/assets/images/lp-icons/SPORE.png',
  JOE: '/assets/images/lp-icons/JOE.png',
  AVAWARE: '/assets/images/lp-icons/Avaware.png',
  AVALABS: '/assets/images/lp-icons/Avalabs.png',
  SPERPA: '/assets/images/lp-icons/Sherpa.png',
  DL: '/assets/images/lp-icons/DL.png',
  OG: '/assets/images/lp-icons/OG.png',
  YAK: '/assets/images/lp-icons/YAK.png',
  YOUTUBE: '/assets/images/lp-icons/Youtube.png',
  NoIcon: '/assets/images/no-image.png',
})

export default LP_ICONS;